apiVersion: apps/v1
kind: Deployment
metadata:
  name: lenslocked-db-deployment
  labels:
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: database
  template:
    metadata:
      labels:
        tier: database
    spec:
      containers:
      - name: lenslocked-database-pod
        image: postgres
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: baloo
          - name: POSTGRES_PASSWORD
            value: junglebook
          - name: POSTGRES_DB
            value: lenslocked