apiVersion: v1
kind: Service
metadata:
  name: lenslocked-service
spec:
  selector:
    app: lenslocked
    tier: webserver
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30008
